version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Update repo on iswenzz.com
          command: 'curl -k "https://iswenzz.com/gitpull?name=simplon_exo"'
